{
  "image": "node:14",
  "stages": [
    "test",
    "deploy"
  ],
  "test": {
    "stage": "test",
    "script": ["npm run test"],
    "except": ["master"]
  },
  "pages": {
    "stage": "deploy",
    "script": ["npm run deploy"],
    "environment": "pages",
    "artifacts": {
      "paths": ["public"]
    },
    "only": ["master"]
  }
}
