{
  "image": "node:16",
  "stages": [
    "test",
    "deploy"
  ],
  "test": {
    "stage": "test",
    "script": ["apt-get update", "apt-get install -y libncurses5", "npm ci", "npm run test"],
    "except": ["master"]
  },
  "pages": {
    "stage": "deploy",
    "script": ["apt-get update", "apt-get install -y libncurses5", "npm run deploy"],
    "environment": "pages",
    "artifacts": {
      "paths": ["public"]
    },
    "only": ["master"]
  },
  "deploy_dev": {
    "stage": "deploy",
    "script": ["apt-get update", "apt-get install -y libncurses5", "npm run deploy"],
    "environment": {
      "name": "dev/$CI_COMMIT_REF_NAME",
      "url": "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
    },
    "artifacts": {
      "paths": ["public"]
    },
    "except": ["master"]
  }
}
