{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a data type for actions in the game.
• Actions can be:
• Making a play
• Canceling an active request
• Toggling supply
• Doing nothing
-}
module Domination.UI.Domination.Action where

import Domination.Data.Play (Play)
import Domination.UI.Domination.ActiveState (ActiveState)

data Action
  = MakePlay Play
  | UndoRequest ActiveState
  | ToggleSupply
  | DoNothing
