{-| AI Summary generated by Ollama (llama3.2:3b)
• Module purpose: Define and organize game-related events.
• Key concepts:
‣ Game event data types:
‣ New state update with active state, updated game, and optional play, player index, and state.
‣ Save game event with active state.
‣ Undo game event with active state.
-}
module Domination.UI.Domination.GameEvent where

import Data.Maybe (Maybe)
import Domination.Data.Game (Game)
import Domination.Data.Play (Play)
import Domination.UI.Domination.ActiveState (ActiveState)

data GameEvent
  = NewState
    ActiveState
    (Maybe { play :: Play, playerIndex :: Int, state :: Game })
  | SaveGame ActiveState
  | Undo ActiveState
