{-| AI Summary generated by Ollama (llama3.2:3b)
• Provides a UI component for announcing input events.
• Uses Halogen HTML to render the label and input field.
• Includes an event handler for when the user inputs something.
• State includes an "announce" string.
-}
module Domination.UI.AnnounceInput where

import Prelude

import Domination.UI.Css as Css
import Halogen.HTML (HTML)
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP

type State r =
  { announce :: String
  | r
  }

type RenderInput r1 r a =
  { state :: State r
  , onInput :: String -> a
  | r1
  }

render :: forall s r a r1. RenderInput r1 r a -> HTML s a
render { onInput, state: { announce } } = HH.div
  [ HP.class_ Css.announceInput ]
  [ HH.label_ [ HH.text "Announce: " ]
  , HH.input
    [ HP.type_ HP.InputText
    , HP.value announce
    , HP.placeholder "e.g. wss://p2p-tracker-24is.onrender.com, wss://tracker.btorrent.xyz"
    , HP.required true
    , HE.onValueInput $ onInput
    ]
  ]
