#!/bin/bash
# Updates version numbers in Version.purs and sw.js
#
# Usage:
#   ./bump-version (major|minor|patch|dev)
#
# Options:
#   major - increment major version, reset minor and patch to 0
#   minor - increment minor version, reset patch to 0
#   patch - increment patch version
#   dev   - increment patch version without git commit/tag

set -ue

: "${1?Usage: $0 (major|minor|patch|dev)}"
VERSION_FILE=src/Version.purs
SW_FILE=assets/sw.js

fail () (
  message=$1
  >&2 echo "$message"
  exit 1
)

digits () (
  grep -oP '\d+'
)

version_line () (
  component=$1
  grep "${component} =" $VERSION_FILE
)

version_number () (
  component=$1
  version_line "$component" | digits
)

increment () (
  component=$1
  old=$(version_number "$component")
  new=$((old + 1))
  sed -ri 's/('"$component"' = ).*/\1'"${new}"'/' $VERSION_FILE
)

zero () (
  component=$1
  sed -ri 's/('"$component"' = ).*/\10/' $VERSION_FILE
)

update_files () (
  component=$1
  case $component in
    patch)
      increment patch
      ;;
    minor)
      zero patch
      increment minor
      ;;
    major)
      zero patch
      zero minor
      increment major
      ;;
    *)
      fail "specify major minor or patch, not '${component}'"
      ;;
  esac

  update_service_worker_cache_version
)

file_changed () (
  ! git diff --no-patch --exit-code $VERSION_FILE
)

changes_are_staged () (
  ! git diff --cached --exit-code
)

update_service_worker_cache_version () (
  version=$(read_version)
  sed -ri "s/(^.*CACHE_NAME = ')[^']*('.*$)/\1${version}\2/" $SW_FILE
)

read_version () (
  major=$(version_number major)
  minor=$(version_number minor)
  patch=$(version_number patch)
  echo "v${major}.${minor}.${patch}"
)

add_commit_and_tag_version () (
  version=$(read_version)

  git add $VERSION_FILE $SW_FILE
  git commit -m "$version"
  git tag -a "$version" -m "$version"
)

main () (
  component=$1

  if [ "$component" != "dev" ]; then
    if file_changed
    then
      fail "${VERSION_FILE} is already changed!"
    fi

    if changes_are_staged
    then
      fail "changes are staged! Commit or reset first!"
    fi
  fi

  if [ "$component" = "dev" ]; then
    update_files "patch"
  else
    update_files "$component"
    add_commit_and_tag_version
  fi
)

main "$1"

