{-| AI Summary generated by Ollama (llama3.2:3b)
• Purpose:
• Manage state and events in the application.
• Support various game modes, user input, and message handling.
Key Actions:
• Initialize app state
• Start a new game
• Update player index and count
• Load game requests
• Toggle menu and long game states
• Randomize kingdom settings
• Choose a kingdom
• Handle remote and local messages
-}
module AppAction where

import AppState (AppState)
import Data.Lens.Lens (Lens')
import Domination.Data.Card (CardSpec)
import Domination.UI.Domination.GameEvent (GameEvent)
import Web.Event.Event (Event)

type CardSpecSelection = { cardSpec :: CardSpec, selected :: Boolean }

data AppAction
  = Initialize
  | StartNewGame
  | WritePlayerIndex Int
  | WritePlayerCount Int
  | LoadGameRequest
  | ToggleMenu
  | ToggleLongGame
  | RandomizeKingdom
  | ChooseKingdom (Array CardSpecSelection)
  | WriteAnnounce String
  | WriteUsername String
  | Write (Lens' AppState String) String
  | SendMessage
  | ReceiveRemoteMessage Event
  | ReceiveLocalMessage Event
  | HandleGameEvent GameEvent
  | DoNothing
