{-| AI Summary generated by Ollama (llama3.2:3b)
• A high-level, functional programming module.
• Purpose:
• Enables a compositional, effectful programming paradigm.
• Facilitates the creation of modular, reusable code.
• Provides a common interface for different effects.
-}
module Domination.AppM where

import Prelude

import Control.Monad.Reader.Trans (ReaderT, runReaderT)
import Domination.Env (Env)
import Effect.Aff (Aff)
import Effect.Aff.Class (class MonadAff)
import Effect.Class (class MonadEffect)

newtype AppM a = AppM (ReaderT Env Aff a)

runAppM :: Env -> AppM ~> Aff
runAppM env (AppM m) = runReaderT m env

derive newtype instance functorAppM :: Functor AppM
derive newtype instance applyAppM :: Apply AppM
derive newtype instance applicativeAppM :: Applicative AppM
derive newtype instance bindAppM :: Bind AppM
derive newtype instance monadAppM :: Monad AppM
derive newtype instance monadEffectAppM :: MonadEffect AppM
derive newtype instance monadAffAppM :: MonadAff AppM
