{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a data structure called "Env" that represents the game environment.
• Currently, it has no additional information or fields.
-}
module Domination.Env where

type Env = {}
