{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a data type for representing version numbers with major, minor, and patch components.
• Provides a value holding the current application version.
• Allows access to the current application version via import.
-}

module Version where

data Version = Version Int Int Int

version :: Version
version = Version major minor patch where
  major = 0
  minor = 33
  patch = 3
