{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a category structure on functions.
• Focuses on associativity rules for function composition.
• Includes left and right associativity requirements.
-}
module Data.AssociativeCategory where

import Data.Tuple (Tuple(..))

class AssociativeCategory k where
  rassoc
    :: forall a b c
    . k (Tuple (Tuple a b) c) (Tuple a (Tuple b c))
  lassoc
    :: forall a b c
    . k (Tuple a (Tuple b c)) (Tuple (Tuple a b) c)

instance associativeCategoryFunction :: AssociativeCategory (->) where
  rassoc (Tuple (Tuple a b) c) = Tuple a (Tuple b c)
  lassoc (Tuple a (Tuple b c)) = Tuple (Tuple a b) c
