{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines data type `Bonus` with two variants: `Cash Int`.
• Provides function to calculate total value of array of bonuses.
• Derives instances for:
• Generic and generic show for `Bonus`.
• Eq, EncodeJson, DecodeJson, and Hashable for `Bonus`.
-}
module Domination.Data.Bonus where

import Prelude

import Data.Argonaut.Decode.Class (class DecodeJson)
import Data.Argonaut.Decode.Generic (genericDecodeJson)
import Data.Argonaut.Encode.Class (class EncodeJson)
import Data.Argonaut.Encode.Generic (genericEncodeJson)
import Data.Array (foldr)
import Data.Generic.Rep (class Generic)
import Data.Hashable (class Hashable)
import Data.Show.Generic (genericShow)

data Bonus
  = Cash Int

cashValue :: Array Bonus -> Int
cashValue = foldr (\a b -> cashValue1 a + b) zero

cashValue1 :: Bonus -> Int
cashValue1 = case _ of
  Cash c -> c

derive instance genericBonus :: Generic Bonus _

derive instance eqBonus :: Eq Bonus

instance showBonus :: Show Bonus where show = genericShow

instance encodeJsonBonus :: EncodeJson Bonus where
  encodeJson a = genericEncodeJson a

instance decodeJsonBonus :: DecodeJson Bonus where
  decodeJson a = genericDecodeJson a

instance hashableBonus :: Hashable Bonus where
  hash = cashValue1
