{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a category theory concept for swapping elements in a tuple.
• Provides an instance for the -> type, which swaps function arguments.
-}
module Data.BraidedCategory where

import Data.Tuple (Tuple(..))

class BraidedCategory k where
  swap :: forall a b. k (Tuple a b) (Tuple b a)

instance braidedCategoryFunction :: BraidedCategory (->) where
  swap (Tuple a b) = Tuple b a
