{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a class for extracting and duplicating elements from functions.
• Provides instances for the type of function that always returns its first argument.
• Allows extraction of left and right arguments, as well as duplication.
-}
module Data.Cartesian where

import Data.Tuple (Tuple(..), fst, snd)

class Cartesian k where
  extractLeft :: forall a b. k (Tuple a b) a
  extractRight :: forall a b. k (Tuple a b) b
  duplicate :: forall a. k a (Tuple a a)

instance cartesianFunction :: Cartesian (->) where
  extractLeft = fst
  extractRight = snd
  duplicate a = Tuple a a
