{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines data types and functions for constraints in the game.
• Represents different types of constraints using distinct types.
• Provides utility functions for checking constraints against given conditions.
Key constraint types:
- UpTo: cards must be less than or equal to a certain number
- Exactly: cards must exactly match a certain number
- DownTo: cards must be greater than or equal to a certain number
- Unlimited: no card count restrictions
• Integrates with existing modules and data structures, such as rules and relationships.
-}
module Domination.Data.Constraint where

import Prim hiding (Constraint)

import Control.Applicative (pure)
import Control.Monad.Error.Class (class MonadError)
import Control.Semigroupoid ((>>>))
import Data.Argonaut.Decode.Class (class DecodeJson)
import Data.Argonaut.Decode.Generic (genericDecodeJson)
import Data.Argonaut.Encode.Class (class EncodeJson)
import Data.Argonaut.Encode.Generic (genericEncodeJson)
import Data.Array (length)
import Data.Eq (class Eq)
import Data.Function (($))
import Data.Generic.Rep (class Generic)
import Data.Show.Generic (genericShow)
import Data.HeytingAlgebra ((&&), (||))
import Data.Semiring (zero)
import Data.Show (class Show)
import Data.Unit (Unit, unit)
import Relationship (Relationship(..))
import Rule (lengthIs, (<>!), (<@!))
import Rule as Rule

data Constraint
  = UpTo Int
  | Exactly Int
  | DownTo Int
  | Unlimited

check
  :: forall m a
  . MonadError String m
  => Show a
  => Constraint
  -> Array a
  -> Array a
  -> Array a
  -> m Unit
check constraint selected remaining sourcePile =
  let
    forSelected = ("selected cards" <>! _) >>> (selected <@! _)
    forRemaining = ("remaining cards" <>! _) >>> (remaining <@! _)
    forSource = ("source cards" <>! _) >>> (sourcePile <@! _)
  in
  case constraint of
    UpTo n -> Rule.check $
      forSelected $ lengthIs LTE n

    DownTo n -> Rule.check $
      forRemaining (lengthIs EQ n)
      ||
      ( forSource (lengthIs LT n)
      && forSelected (lengthIs EQ zero)
      )

    Exactly n -> Rule.check $
      forSelected (lengthIs EQ n)
      ||
      ( forSource (lengthIs LT n)
      && forSelected (lengthIs EQ $ length sourcePile)
      )

    Unlimited -> pure unit

derive instance genericConstraint :: Generic Constraint _
derive instance eqConstraint :: Eq Constraint

instance showConstraint :: Show Constraint where
  show = genericShow
instance encodeJsonConstraint :: EncodeJson Constraint where
  encodeJson = genericEncodeJson
instance decodeJsonConstraint :: DecodeJson Constraint where
  decodeJson = genericDecodeJson
