{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a data type for filters.
• Supports encoding and decoding to/from JSON.
• Includes variants for filtering by name, card type, cost, or combining conditions using 'and'.
• Provides generic instances for equality, ordering, and show.
-}
module Domination.Data.Filter where

import Prelude

import Data.Argonaut.Decode.Class (class DecodeJson)
import Data.Argonaut.Decode.Generic (genericDecodeJson)
import Data.Argonaut.Encode.Class (class EncodeJson)
import Data.Argonaut.Encode.Generic (genericEncodeJson)
import Data.Generic.Rep (class Generic)
import Data.Show.Generic (genericShow)
import Domination.Data.CardType (CardType)

data Filter
  = HasName String
  | HasType CardType
  | CostUpTo Int
  | Any
  | And Filter Filter

derive instance genericFilter :: Generic Filter _
derive instance eqFilter :: Eq Filter
instance showFilter :: Show Filter where
  show condition = genericShow condition
instance encodeJsonFilter :: EncodeJson Filter where
  encodeJson a = genericEncodeJson a
instance decodeJsonFilter :: DecodeJson Filter where
  decodeJson a = genericDecodeJson a
