{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines two algebraic structures:
• Join semilattice: operation that returns the greatest lower bound of two elements
• Meet semilattice: operation that returns the least upper bound of two elements
• Extends these structures to functions using function application
• Introduces bounds (bottom and top) for join and meet semilattres
-}
module Domination.Data.Lattice where

class JoinSemilattice a where
  join :: a -> a -> a

infixr 4 join as \/

instance joinSemilatticeFunction
  :: JoinSemilattice b => JoinSemilattice (a -> b) where
  join f g a = f a \/ g a

class MeetSemilattice a where
  meet :: a -> a -> a

instance meetSemilatticeFunction
  :: MeetSemilattice b => MeetSemilattice (a -> b) where
  meet f g a = f a /\ g a

infixr 4 meet as /\

class JoinSemilattice a <= BoundedJoinSemilattice a where
  bottom :: a

class MeetSemilattice a <= BoundedMeetSemilattice a where
  top :: a
