{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a class for a type that supports a monoidal product.
• Provides a way to combine two instances of the same type into a new instance.
• Allows extracting individual components from a combined instance.
Key methods:
- cross: combines two instances
- first, second: extract individual components
-}
module Data.MonoidalProduct where

import Control.Category ((<<<))
import Data.BraidedCategory (swap)
import Data.Tuple (Tuple(..))

class MonoidalProduct k where
  cross :: forall a b c d. k a c -> k b d -> k (Tuple a b) (Tuple c d)
  first :: forall a b c. k a c -> k (Tuple a b) (Tuple c b)
  second :: forall a b d. k b d -> k (Tuple a b) (Tuple a d)

instance monoidalProductFunction :: MonoidalProduct (->) where
  cross f g = first f <<< second g
  first f (Tuple a b) = Tuple (f a) b
  second g = swap <<< first g <<< swap
