{-| AI Summary generated by Ollama (llama3.2:3b)
• Defines a data type representing different groups of people.
• Provides instances for generic and JSON-specific encoding/decoding.
• Data type: Target (Self, Everyone, EveryoneElse)
• Generic representations:
• Generic instance: genericTarget
• Generic value equality: eqTarget
• JSON-related representations:
• Show instance: showTarget
• EncodeJson instance: encodeJsonTarget
• DecodeJson instance: decodeJsonTarget
-}
module Domination.Data.Target where

import Prelude

import Data.Argonaut.Decode.Class (class DecodeJson)
import Data.Argonaut.Decode.Generic (genericDecodeJson)
import Data.Argonaut.Encode.Class (class EncodeJson)
import Data.Argonaut.Encode.Generic (genericEncodeJson)
import Data.Generic.Rep (class Generic)
import Data.Show.Generic (genericShow)

data Target
  = Self
  | Everyone
  | EveryoneElse

derive instance genericTarget :: Generic Target _
derive instance eqTarget :: Eq Target

instance showTarget :: Show Target where
  show = genericShow
instance encodeJsonTarget :: EncodeJson Target where
  encodeJson = genericEncodeJson
instance decodeJsonTarget :: DecodeJson Target where
  decodeJson = genericDecodeJson
